language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t kharrazkarim/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true kharrazkarim/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $Access_key_ID
  secret_access_key: $Secret_access_key
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-659616336599"
  bucket_path: "docker-react"
  edge: true # opt in to dpl v2
  on:
    branch: master
   