language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t kharrazkarim/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true kharrazkarim/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: <encrypted access_key_id>
  secret_access_key: <encrypted secret_access_key>
  bucket: <bucket>
  edge: true # opt in to dpl v2
  on:
    branch: master
   