language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t kharrazkarim/docker-react -f Dockerfile.dev .
script:
  - docker run kharrazkarim/docker-react -e CI=true  npm run test -- --coverage
